import { ThemeToggle } from "@/components/ThemeToggle";

export default function Home() {
  return (
    <main className=" gap-4">
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <h1>Learn Doc</h1>
      <ThemeToggle />
    </main>
  );
}
